version: "3.9"
services:
  api:
    image: api:0.1
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - API_PORT=8000
      - API_HOST=0.0.0.0
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_HOST=database
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
