version: '3.10'
services:
  api:
    image: api:0.1
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      API_PORT: 8000
      API_HOST: 0.0.0.0
      DATABSE_HOST: database
      DATABSE_USER: tyro
      DATABSE_PASSWORD: $password$ 
      GCP_PROJECT_ID: $GCP_PROJECT_ID
      GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET
      GCP_CREDENTIALS_ENCODED: $GCP_CREDENTIALS_ENCODED
  database: 
    image: mongo:6.0.7
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: tyro
      MONGO_INITDB_ROOT_PASSWORD: $password$
      MONGO_INITDB_DATABASE: tyroapp
