FROM continuumio/miniconda3

COPY main.py /app/main.py
COPY requirements.txt /app/requirements.txt

RUN conda config --add channels conda-forge
RUN conda env create --name virtual-env --file /app/requirements.txt python=3.9.16

ENTRYPOINT [ "conda", "run", "-n", "virtual-env", "--no-capture-output", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]