apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: admin
      containers:
      - name: api
        image: api:0.1
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            memory: 400Mi
            cpu: 200m 
        env:
          - name: POSTGRES_HOST
            value: "database-service"
          - name: POSTGRES_PASSWORD
            value: "postgres"


      