name: CI
run-name: Running CI pipeline for ${{ github.actor }}

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  tests:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Prepare and Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8

      - name: Black analysis
        run: |
          black --check .

      - name: Flake8 analysis
        run: |
          flake8 .
